name: com.mcgod.MCGodMain
version: 1.0.1
api-version: "1.13"
main: com.mcgod.MCGodMain
description: A fun Java plugin that adds ChatGPT as a god that can modify a server's Minecraft World.
commands:
  pray:
    description: Pray to ChatGPT for help
    usage: /<command> <message>
  advice:
    description: Ask ChatGPT for advice on anything
    usage: /<command> <message>
  spy:
    description: Ask ChatGPT to spy on a player and get information
    usage: /<command> <message>
  sacrifice:
    description: Sacrifice an item to ChatGPT when near a holy site
    usage: /<command>
  start:
    description: Start the ChatGPT plugin
    usage: /<command>
  stop:
    description: Stop the ChatGPT plugin
    usage: /<command>
