name: MCGod
version: 1.0.2
api-version: "1.20.6"
main: com.mcgod.MCGodMain
description: A fun Java plugin that adds ChatGPT as a god that can modify a server's Minecraft World.
commands:
  
  pray:
    description: Pray to ChatGPT for help
    usage: /<command> <message>
  advice:
    description: Ask ChatGPT for advice on anything
    usage: /<command> <message>
  spy:
    description: Ask ChatGPT to spy on a player and get information
    usage: /<command> <message>
  sacrifice:
    description: Sacrifice an item to ChatGPT when near a holy site
    usage: /<command>
  start_quest:
    description: Starts a new quest
    usage: /<command>
  quest_reminder:
    description: Reminds the player of their current quest
    usage: /<command>
  end_quest:
    description: Ends the current quest and provides a reward
    usage: /<command>
  start:
    description: Start the ChatGPT plugin
    usage: /<command>
  stop:
    description: Stop the ChatGPT plugin
    usage: /<command>